version: '3'

services:
    build-graph-mato:
        image: registry:5000/opentripplannerwc
        build: .
        container_name: build-graph-mato
        volumes:
            - /data/otp-graphs/:/var/otp/graphs/
        network_mode: bridge
        command: java -Xms4G -Xmx4G -Duser.timezone="Europe/Rome" -jar ./otp-shaded.jar --verbose --build ./graphs/mato

    run-otp-mato:
        image: registry:5000/opentripplannerwc
        container_name: run-otp-mato
        volumes:
            - /data/otp-graphs/:/var/otp/graphs/
        ports:
            - 8070:8080
        restart: unless-stopped
        network_mode: bridge
        command: java -Xms4G -Xmx4G -Duser.timezone="Europe/Rome" -jar ./otp-shaded.jar --verbose --server --port 8080 --graphs ./graphs --router mato
