version: '3'

services:
    otp-mato-build-graph:
        image: registry:5000/opentripplannerwc
        build: .
        container_name: otp-mato-build-graph
        volumes:
            - /data/otp-graphs/:/var/otp/graphs/
        network_mode: bridge
        command: java -Xms4G -Xmx4G -jar otp-shaded.jar --build ./graphs/mato

    otp-run-mato:
        image: registry:5000/opentripplannerwc
        container_name: otp-run-mato
        volumes:
            - /data/otp-graphs/:/var/otp/graphs/
        ports:
            - 8070:8080
        restart: unless-stopped
        network_mode: bridge
        command: java -Xms4G -Xmx4G -Duser.timezone="Europe/Rome" -jar ./otp-shaded.jar --verbose --server --port 8080 --graphs ./graphs --router mato
